import { defineConfig } from 'unocss'
import { unoColors, unoPresets, unoShortcuts, unoTransformers } from '@edtaxi/shared/uno.base'

export default defineConfig({
  shortcuts: [
    ...unoShortcuts,
  ],
  theme: {
    colors: unoColors,
  },
  presets: unoPresets,
  transformers: unoTransformers,
  safelist: [
    ...'prose prose-sm m-auto text-left'.split(' '),
    'i-mdi-airplane',
    'i-mdi-alert',
    'i-mdi-alert-circle',
    'i-mdi-cash-multiple',
    'i-mdi-cash-refund',
    'i-mdi-car-clock',
    'i-mdi-car-hatchback',
    'i-mdi-car-info',
    'i-mdi-car-seat',
    'i-mdi-cellphone-check',
    'i-mdi-check',
    'i-mdi-check-circle',
    'i-mdi-clock-outline',
    'i-mdi-close-circle',
    'i-mdi-cog-outline',
    'i-mdi-diamond-stone',
    'i-mdi-flag-checkered',
    'i-mdi-headset',
    'i-mdi-information',
    'i-mdi-loading',
    'i-mdi-map-marker-check',
    'i-mdi-map-marker-outline',
    'i-mdi-map-marker-path',
    'i-mdi-navigation-variant',
    'i-mdi-play-circle',
    'i-mdi-plus-circle',
    'i-mdi-radar',
    'i-mdi-share-variant',
    'i-mdi-taxi',
    'i-mdi-telegram',
    'i-mdi-van-passenger',
    'i-mdi-view-grid-outline',
    'i-mdi-wallet-outline',
    'i-mdi-whatsapp',
    'i-mdi-message-text-outline',
  ],
})
