/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSelectDropdown: typeof import('./components/app/AppSelectDropdown.vue')['default']
    AppToaster: typeof import('./components/app/AppToaster.vue')['default']
    AuthButton: typeof import('./components/auth/AuthButton.vue')['default']
    AuthError: typeof import('./components/auth/AuthError.vue')['default']
    AuthLoginForm: typeof import('./components/auth/AuthLoginForm.vue')['default']
    AuthScreen: typeof import('./components/auth/AuthScreen.vue')['default']
    DemandOverviewSection: typeof import('./components/admin/settings/DemandOverviewSection.vue')['default']
    HourlyForecastSection: typeof import('./components/admin/settings/HourlyForecastSection.vue')['default']
    NavigationComponent: typeof import('./components/NavigationComponent.vue')['default']
    OtpInput: typeof import('./components/auth/OtpInput.vue')['default']
    OtpSelect: typeof import('./components/auth/OtpSelect.vue')['default']
    PhoneInput: typeof import('./components/auth/PhoneInput.vue')['default']
    PlatformCommissionForm: typeof import('./components/admin/settings/PlatformCommissionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportChatHeader: typeof import('./components/support/SupportChatHeader.vue')['default']
    SupportClientPanel: typeof import('./components/support/SupportClientPanel.vue')['default']
    SupportMessageList: typeof import('./components/support/SupportMessageList.vue')['default']
    SupportReplyForm: typeof import('./components/support/SupportReplyForm.vue')['default']
    TariffsSection: typeof import('./components/admin/settings/TariffsSection.vue')['default']
    WebPageShell: typeof import('./components/app/WebPageShell.vue')['default']
  }
}
