/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminOverviewSection: typeof import('./components/admin/overview/AdminOverviewSection.vue')['default']
    AdminSidebar: typeof import('./components/admin/AdminSidebar.vue')['default']
    AppSelectDropdown: typeof import('./components/app/AppSelectDropdown.vue')['default']
    AppToaster: typeof import('./components/app/AppToaster.vue')['default']
    AuthButton: typeof import('./components/auth/AuthButton.vue')['default']
    AuthError: typeof import('./components/auth/AuthError.vue')['default']
    AuthLoginForm: typeof import('./components/auth/AuthLoginForm.vue')['default']
    AuthScreen: typeof import('./components/auth/AuthScreen.vue')['default']
    CityStatsCard: typeof import('./components/admin/overview/CityStatsCard.vue')['default']
    DemandOverviewSection: typeof import('./components/admin/settings/DemandOverviewSection.vue')['default']
    HourlyForecastSection: typeof import('./components/admin/settings/HourlyForecastSection.vue')['default']
    KpiStatCard: typeof import('./components/app/KpiStatCard.vue')['default']
    NavigationComponent: typeof import('./components/NavigationComponent.vue')['default']
    OtpInput: typeof import('./components/auth/OtpInput.vue')['default']
    OtpSelect: typeof import('./components/auth/OtpSelect.vue')['default']
    ParkAnalyticsSection: typeof import('./components/park/ParkAnalyticsSection.vue')['default']
    ParkChangeRequestModal: typeof import('./components/park/ParkChangeRequestModal.vue')['default']
    ParkDriversSection: typeof import('./components/park/ParkDriversSection.vue')['default']
    ParkEditModal: typeof import('./components/park/ParkEditModal.vue')['default']
    ParkInviteQrModal: typeof import('./components/park/ParkInviteQrModal.vue')['default']
    ParkInviteSection: typeof import('./components/park/ParkInviteSection.vue')['default']
    ParkModal: typeof import('./components/park/ParkModal.vue')['default']
    ParkProfileCard: typeof import('./components/park/ParkProfileCard.vue')['default']
    ParkSidebar: typeof import('./components/park/ParkSidebar.vue')['default']
    PhoneInput: typeof import('./components/auth/PhoneInput.vue')['default']
    PlatformCommissionForm: typeof import('./components/admin/settings/PlatformCommissionForm.vue')['default']
    PromotionForm: typeof import('./components/promotions/PromotionForm.vue')['default']
    PromotionsList: typeof import('./components/promotions/PromotionsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatBarChart: typeof import('./components/charts/StatBarChart.vue')['default']
    StatChartCard: typeof import('./components/charts/StatChartCard.vue')['default']
    SupportChatHeader: typeof import('./components/support/SupportChatHeader.vue')['default']
    SupportClientPanel: typeof import('./components/support/SupportClientPanel.vue')['default']
    SupportMessageList: typeof import('./components/support/SupportMessageList.vue')['default']
    SupportReplyForm: typeof import('./components/support/SupportReplyForm.vue')['default']
    TariffsSection: typeof import('./components/admin/settings/TariffsSection.vue')['default']
    WebPageShell: typeof import('./components/app/WebPageShell.vue')['default']
  }
}
