/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/districts': RouteRecordInfo<
      '/admin/districts',
      '/admin/districts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/feedback': RouteRecordInfo<
      '/admin/feedback',
      '/admin/feedback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/garage': RouteRecordInfo<
      '/admin/garage',
      '/admin/garage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/park-chats': RouteRecordInfo<
      '/admin/park-chats',
      '/admin/park-chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/parks': RouteRecordInfo<
      '/admin/parks',
      '/admin/parks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/payouts': RouteRecordInfo<
      '/admin/payouts',
      '/admin/payouts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/promotions': RouteRecordInfo<
      '/admin/promotions',
      '/admin/promotions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/support-rooms': RouteRecordInfo<
      '/admin/support-rooms',
      '/admin/support-rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tech-support': RouteRecordInfo<
      '/admin/tech-support',
      '/admin/tech-support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/trips': RouteRecordInfo<
      '/admin/trips',
      '/admin/trips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/drivers/[id]': RouteRecordInfo<
      '/drivers/[id]',
      '/drivers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/legal/offer': RouteRecordInfo<
      '/legal/offer',
      '/legal/offer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/privacy': RouteRecordInfo<
      '/legal/privacy',
      '/legal/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/refund': RouteRecordInfo<
      '/legal/refund',
      '/legal/refund',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/requisites': RouteRecordInfo<
      '/legal/requisites',
      '/legal/requisites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/': RouteRecordInfo<
      '/park/',
      '/park',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/chat/': RouteRecordInfo<
      '/park/chat/',
      '/park/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/chat/[id]': RouteRecordInfo<
      '/park/chat/[id]',
      '/park/chat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/park/login': RouteRecordInfo<
      '/park/login',
      '/park/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/promotions': RouteRecordInfo<
      '/park/promotions',
      '/park/promotions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/register': RouteRecordInfo<
      '/park/register',
      '/park/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/requests': RouteRecordInfo<
      '/park/requests',
      '/park/requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/wallet': RouteRecordInfo<
      '/park/wallet',
      '/park/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passengers/[id]': RouteRecordInfo<
      '/passengers/[id]',
      '/passengers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/support/': RouteRecordInfo<
      '/support/',
      '/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/[id]': RouteRecordInfo<
      '/support/[id]',
      '/support/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/support/car-requests': RouteRecordInfo<
      '/support/car-requests',
      '/support/car-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/login': RouteRecordInfo<
      '/support/login',
      '/support/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/trip-chats': RouteRecordInfo<
      '/support/trip-chats',
      '/support/trip-chats',
      Record<never, never>,
      Record<never, never>,
      | '/support/trip-chats/[id]'
    >,
    '/support/trip-chats/[id]': RouteRecordInfo<
      '/support/trip-chats/[id]',
      '/support/trip-chats/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/support/verifications': RouteRecordInfo<
      '/support/verifications',
      '/support/verifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/districts.vue': {
      routes:
        | '/admin/districts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/feedback.vue': {
      routes:
        | '/admin/feedback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/garage.vue': {
      routes:
        | '/admin/garage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/park-chats.vue': {
      routes:
        | '/admin/park-chats'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/parks.vue': {
      routes:
        | '/admin/parks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/payouts.vue': {
      routes:
        | '/admin/payouts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/promotions.vue': {
      routes:
        | '/admin/promotions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/support-rooms.vue': {
      routes:
        | '/admin/support-rooms'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/tech-support.vue': {
      routes:
        | '/admin/tech-support'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/trips.vue': {
      routes:
        | '/admin/trips'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/drivers/[id].vue': {
      routes:
        | '/drivers/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/legal/offer.md': {
      routes:
        | '/legal/offer'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/legal/privacy.md': {
      routes:
        | '/legal/privacy'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/legal/refund.md': {
      routes:
        | '/legal/refund'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/legal/requisites.md': {
      routes:
        | '/legal/requisites'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/index.vue': {
      routes:
        | '/park/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/chat/index.vue': {
      routes:
        | '/park/chat/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/chat/[id].vue': {
      routes:
        | '/park/chat/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/park/login.vue': {
      routes:
        | '/park/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/promotions.vue': {
      routes:
        | '/park/promotions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/register.vue': {
      routes:
        | '/park/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/requests.vue': {
      routes:
        | '/park/requests'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/park/wallet.vue': {
      routes:
        | '/park/wallet'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passengers/[id].vue': {
      routes:
        | '/passengers/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/support/index.vue': {
      routes:
        | '/support/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/support/[id].vue': {
      routes:
        | '/support/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/support/car-requests.vue': {
      routes:
        | '/support/car-requests'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/support/login.vue': {
      routes:
        | '/support/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/support/trip-chats.vue': {
      routes:
        | '/support/trip-chats'
        | '/support/trip-chats/[id]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/support/trip-chats/[id].vue': {
      routes:
        | '/support/trip-chats/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/support/verifications.vue': {
      routes:
        | '/support/verifications'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
