/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressSuggestions: typeof import('./components/driver/AddressSuggestions.vue')['default']
    AppToaster: typeof import('./components/app/AppToaster.vue')['default']
    AuthButton: typeof import('./components/auth/AuthButton.vue')['default']
    AuthError: typeof import('./components/auth/AuthError.vue')['default']
    AuthScreen: typeof import('./components/auth/AuthScreen.vue')['default']
    BottomNav: typeof import('./components/app/BottomNav.vue')['default']
    CatalogRequestBlock: typeof import('./components/vehicle/CatalogRequestBlock.vue')['default']
    DistrictsMiniMap: typeof import('./components/driver/DistrictsMiniMap.vue')['default']
    DriverMap: typeof import('./components/driver/DriverMap.vue')['default']
    DriverStatusPanel: typeof import('./components/driver/DriverStatusPanel.vue')['default']
    DriverTripOffer: typeof import('./components/driver/DriverTripOffer.vue')['default']
    EarningsBarChart: typeof import('./components/driver/EarningsBarChart.vue')['default']
    EarningsChart: typeof import('./components/driver/EarningsChart.vue')['default']
    FaceCaptureCamera: typeof import('./components/verification/FaceCaptureCamera.vue')['default']
    HomeModeSheet: typeof import('./components/driver/HomeModeSheet.vue')['default']
    MapView: typeof import('./components/map/MapView.vue')['default']
    OtpInput: typeof import('./components/auth/OtpInput.vue')['default']
    OtpSelect: typeof import('./components/auth/OtpSelect.vue')['default']
    PassengerMapPicker: typeof import('./components/passenger/PassengerMapPicker.vue')['default']
    PaymentFrameModal: typeof import('./components/PaymentFrameModal.vue')['default']
    PhoneInput: typeof import('./components/auth/PhoneInput.vue')['default']
    RatePassengerModal: typeof import('./components/driver/RatePassengerModal.vue')['default']
    RouteHeader: typeof import('./components/app/RouteHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerificationReminderBanner: typeof import('./components/driver/VerificationReminderBanner.vue')['default']
  }
}
