/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/driver/': RouteRecordInfo<
      '/driver/',
      '/driver',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/earnings': RouteRecordInfo<
      '/driver/earnings',
      '/driver/earnings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/login/': RouteRecordInfo<
      '/driver/login/',
      '/driver/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/login/verify': RouteRecordInfo<
      '/driver/login/verify',
      '/driver/login/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/': RouteRecordInfo<
      '/driver/menu/',
      '/driver/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/onboarding/': RouteRecordInfo<
      '/driver/menu/onboarding/',
      '/driver/menu/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/onboarding/daily-check': RouteRecordInfo<
      '/driver/menu/onboarding/daily-check',
      '/driver/menu/onboarding/daily-check',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/onboarding/face-photo': RouteRecordInfo<
      '/driver/menu/onboarding/face-photo',
      '/driver/menu/onboarding/face-photo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/onboarding/vehicle-docs': RouteRecordInfo<
      '/driver/menu/onboarding/vehicle-docs',
      '/driver/menu/onboarding/vehicle-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/park-invite': RouteRecordInfo<
      '/driver/menu/park-invite',
      '/driver/menu/park-invite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/support': RouteRecordInfo<
      '/driver/menu/support',
      '/driver/menu/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/vehicle': RouteRecordInfo<
      '/driver/menu/vehicle',
      '/driver/menu/vehicle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/driver/index.vue': {
      routes:
        | '/driver/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/earnings.vue': {
      routes:
        | '/driver/earnings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/login/index.vue': {
      routes:
        | '/driver/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/login/verify.vue': {
      routes:
        | '/driver/login/verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/index.vue': {
      routes:
        | '/driver/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/onboarding/index.vue': {
      routes:
        | '/driver/menu/onboarding/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/onboarding/daily-check.vue': {
      routes:
        | '/driver/menu/onboarding/daily-check'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/onboarding/face-photo.vue': {
      routes:
        | '/driver/menu/onboarding/face-photo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/onboarding/vehicle-docs.vue': {
      routes:
        | '/driver/menu/onboarding/vehicle-docs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/park-invite.vue': {
      routes:
        | '/driver/menu/park-invite'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/support.vue': {
      routes:
        | '/driver/menu/support'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/driver/menu/vehicle.vue': {
      routes:
        | '/driver/menu/vehicle'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
