/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/earnings': RouteRecordInfo<
      '/earnings',
      '/earnings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/verify': RouteRecordInfo<
      '/login/verify',
      '/login/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/map': RouteRecordInfo<
      '/map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/': RouteRecordInfo<
      '/menu/',
      '/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/onboarding/': RouteRecordInfo<
      '/menu/onboarding/',
      '/menu/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/onboarding/daily-check': RouteRecordInfo<
      '/menu/onboarding/daily-check',
      '/menu/onboarding/daily-check',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/onboarding/face-photo': RouteRecordInfo<
      '/menu/onboarding/face-photo',
      '/menu/onboarding/face-photo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/onboarding/vehicle-docs': RouteRecordInfo<
      '/menu/onboarding/vehicle-docs',
      '/menu/onboarding/vehicle-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/park-invite': RouteRecordInfo<
      '/menu/park-invite',
      '/menu/park-invite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/support': RouteRecordInfo<
      '/menu/support',
      '/menu/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/vehicle': RouteRecordInfo<
      '/menu/vehicle',
      '/menu/vehicle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/earnings.vue': {
      routes:
        | '/earnings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/verify.vue': {
      routes:
        | '/login/verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/map.vue': {
      routes:
        | '/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/index.vue': {
      routes:
        | '/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/onboarding/index.vue': {
      routes:
        | '/menu/onboarding/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/onboarding/daily-check.vue': {
      routes:
        | '/menu/onboarding/daily-check'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/onboarding/face-photo.vue': {
      routes:
        | '/menu/onboarding/face-photo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/onboarding/vehicle-docs.vue': {
      routes:
        | '/menu/onboarding/vehicle-docs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/park-invite.vue': {
      routes:
        | '/menu/park-invite'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/support.vue': {
      routes:
        | '/menu/support'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/vehicle.vue': {
      routes:
        | '/menu/vehicle'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
