/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressForm: typeof import('./components/passenger/downbar/AddressForm.vue')['default']
    AddressSuggestions: typeof import('./components/passenger/downbar/AddressSuggestions.vue')['default']
    AppToaster: typeof import('./components/app/AppToaster.vue')['default']
    AuthButton: typeof import('./components/auth/AuthButton.vue')['default']
    AuthError: typeof import('./components/auth/AuthError.vue')['default']
    AuthScreen: typeof import('./components/auth/AuthScreen.vue')['default']
    Avatar: typeof import('./components/passenger/Avatar.vue')['default']
    BottomNav: typeof import('./components/app/BottomNav.vue')['default']
    Downbar: typeof import('./components/passenger/Downbar.vue')['default']
    MapView: typeof import('./components/map/MapView.vue')['default']
    OtpInput: typeof import('./components/auth/OtpInput.vue')['default']
    OtpSelect: typeof import('./components/auth/OtpSelect.vue')['default']
    PassengerMap: typeof import('./components/passenger/PassengerMap.vue')['default']
    PassengerMapPicker: typeof import('./components/passenger/PassengerMapPicker.vue')['default']
    PaymentFrameModal: typeof import('./components/PaymentFrameModal.vue')['default']
    PhoneInput: typeof import('./components/auth/PhoneInput.vue')['default']
    RouteHeader: typeof import('./components/app/RouteHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchingTrip: typeof import('./components/passenger/downbar/SearchingTrip.vue')['default']
    TariffList: typeof import('./components/passenger/downbar/TariffList.vue')['default']
  }
}
