/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/bonus': RouteRecordInfo<
      '/bonus',
      '/bonus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/accounts': RouteRecordInfo<
      '/login/accounts',
      '/login/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/phone': RouteRecordInfo<
      '/login/phone',
      '/login/phone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/verify': RouteRecordInfo<
      '/login/verify',
      '/login/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/map': RouteRecordInfo<
      '/map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/': RouteRecordInfo<
      '/menu/',
      '/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/about': RouteRecordInfo<
      '/menu/about',
      '/menu/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/change-phone': RouteRecordInfo<
      '/menu/change-phone',
      '/menu/change-phone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/history': RouteRecordInfo<
      '/menu/history',
      '/menu/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/places': RouteRecordInfo<
      '/menu/places',
      '/menu/places',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/profile/': RouteRecordInfo<
      '/menu/profile/',
      '/menu/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/safety': RouteRecordInfo<
      '/menu/safety',
      '/menu/safety',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/settings': RouteRecordInfo<
      '/menu/settings',
      '/menu/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/support': RouteRecordInfo<
      '/menu/support',
      '/menu/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/trip-chat': RouteRecordInfo<
      '/trip-chat',
      '/trip-chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/wallet': RouteRecordInfo<
      '/wallet',
      '/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/bonus.vue': {
      routes:
        | '/bonus'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/accounts.vue': {
      routes:
        | '/login/accounts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/phone.vue': {
      routes:
        | '/login/phone'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/verify.vue': {
      routes:
        | '/login/verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/map.vue': {
      routes:
        | '/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/index.vue': {
      routes:
        | '/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/about.vue': {
      routes:
        | '/menu/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/change-phone.vue': {
      routes:
        | '/menu/change-phone'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/history.vue': {
      routes:
        | '/menu/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/places.vue': {
      routes:
        | '/menu/places'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/profile/index.vue': {
      routes:
        | '/menu/profile/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/safety.vue': {
      routes:
        | '/menu/safety'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/settings.vue': {
      routes:
        | '/menu/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/support.vue': {
      routes:
        | '/menu/support'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/trip-chat.vue': {
      routes:
        | '/trip-chat'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/wallet.vue': {
      routes:
        | '/wallet'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
