/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/passenger/': RouteRecordInfo<
      '/passenger/',
      '/passenger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/login/': RouteRecordInfo<
      '/passenger/login/',
      '/passenger/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/login/verify': RouteRecordInfo<
      '/passenger/login/verify',
      '/passenger/login/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/': RouteRecordInfo<
      '/passenger/menu/',
      '/passenger/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/history': RouteRecordInfo<
      '/passenger/menu/history',
      '/passenger/menu/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/places': RouteRecordInfo<
      '/passenger/menu/places',
      '/passenger/menu/places',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/settings': RouteRecordInfo<
      '/passenger/menu/settings',
      '/passenger/menu/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/support': RouteRecordInfo<
      '/passenger/menu/support',
      '/passenger/menu/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/wallet': RouteRecordInfo<
      '/passenger/wallet',
      '/passenger/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/passenger/index.vue': {
      routes:
        | '/passenger/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/login/index.vue': {
      routes:
        | '/passenger/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/login/verify.vue': {
      routes:
        | '/passenger/login/verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/menu/index.vue': {
      routes:
        | '/passenger/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/menu/history.vue': {
      routes:
        | '/passenger/menu/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/menu/places.vue': {
      routes:
        | '/passenger/menu/places'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/menu/settings.vue': {
      routes:
        | '/passenger/menu/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/menu/support.vue': {
      routes:
        | '/passenger/menu/support'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/passenger/wallet.vue': {
      routes:
        | '/passenger/wallet'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
